import type { Metadata } from "next";
import { getThemeFromCookie } from "@/helper/cookiesFunction";
import { GlobalThemeContextProvider } from "@/contexts/GlobalTheme";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = getThemeFromCookie();
  return <GlobalThemeContextProvider initialTheme={theme}>{children}</GlobalThemeContextProvider>;
}
